### ISSUE TITLE
[Request] MR32 and MR33 support?

### ISSUE THREAD

**Issue by GravitySandwichh** [clayface/openwrt-cryptid#1]
Would it be possible to add MR32 and MR33 support? I have a few of these AP's laying around and they are currently not flashable due to having a too new u-boot.

**Comment by clayface** [comment]
Hi, [MR32](https://openwrt.org/toh/meraki/mr32) and [MR33](https://openwrt.org/toh/meraki/mr33) support have been added separately (not by me), but Meraki closed off the install methods for both devices. Please check the links for more info.
